### PR TITLE
Added a syncStarted signal to Connection

### PR DESCRIPTION
**Pull request by andir**

### CODE REVIEW

**Comment by KitsuneRal** [comment]
If implemented that way, the name is a bit misleading: you're emitting a signal at the start of _processing_ the sync data that arrived from the server, not at the start of the actual call to the server. What task are you trying to solve? Let's find the right way of doing it together.

**Comment by andir** [comment]
Oh right... I'd really like to start at the beginning of the request not on handling the response. What I'm trying to do is adding a bit more user feedback to the client. So It will display that it is currently syncing.. Would be a better experience if you can be sure the damn thing isn't stuck anywhere.

**Comment by andir** [comment]
The right approach would be to move the `emit syncStarted();` right before the `start()` call?
The reason I'd not put it after the call to `->start()` is that I believe due to threading and such the start emit could occur after the request has finished. But I'm not an expert on how QT handles this.

**Comment by KitsuneRal** [comment]
Do you want to introduce that for Quaternion or some other client? As I described in #quaternion:matrix.org, Quaternion currently acts in such a way that you'll see it's "currently syncing" almost always.
Your idea still makes perfect sense if another client uses sync requests in a different way. And if we go that way, it might make sense to have a signal emitted for any request sent to the server, how do you think?

**Comment by andir** [comment]
Quaternion was my intend. I've not seen the "currently syncing" state while using Quaternion yet.  Emitting it for every event would make sense.

**Comment by KitsuneRal** [comment]
I'm afraid you're out of luck then. What I meant to say is that Quaternion is constantly waiting for a sync response from the server. Once it finishes processing the sync response it immediately fires the next request (you can see it in [this part of Quaternion code, syncDone -> gotEvents -> getNewEvents](https://github.com/Fxrh/Quaternion/blob/master/client/mainwindow.cpp#L91) ).

**Comment by andir** [comment]
Now the code that I saw does make sense.. I'll have to dig a bit deeper and read more about the protocol before going further down that road I guess... I'll close this PR for now.

**Comment by KitsuneRal** [comment]
As a postscriptum, the thing still would make sense for other jobs as well as for other clients. And then a place for emitting such signal would be in the very beginning of BaseJob::start() - by default, connections to signals within the same thread (and BaseJob::start is invoked from the UI thread) are marshalled immediately so you could actually show something in, say, a status bar. But then there's another tricky question about determining the type and details of the job - the signal from BaseJob would only carry a pointer to BaseJob. I have added job names recently but that's only so much for now. Feel free to return to the topic when you consider you're ready.

**Pull request closed without merging**
